# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f6234b7901e447f2d8e42607896d19fde133d656a92da261774fea4aa203521dda3538d242175a68d7abd1132ef97917b75e5b047feda968736aed9b45c7dd5

test:
  secret_key_base: 36128a4569e3ae29c29a90a6c9049860c83b69ed84330ccb19a16642e44cf996c4f6bcb437ab124eb42d3abf8b9dcfff2fea8f5be23ca810dc1f9adf48919898

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
